version: "3.8"
services:
  php-apache:
    build: .
    image: php_apache
    container_name: php_apache
    environment:
      DB_HOST: mysql
      DB_PORT: '3306'
      DB_NAME: osxhub_db
      DB_USER: root
      DB_PASS: root
      DB_AUTO_MIGRATE: 'false'
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_project_mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data: